services:

  db_usuarios:
    image: postgres:16
    container_name: postgres-usuarios
    restart: always
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: usuarios
      POSTGRES_PASSWORD: usuarios123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - usuarios-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-usuarios
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db_usuarios
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - usuarios-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  usuarios-network:
    driver: bridge